version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
      MYSQL_DATABASE: bank_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"

volumes:
  mysql_data: